export const EnumCanOrderMenu = {
  RESTAURANT_CLOSED: "RESTAURANT_CLOSED",
  MENU_NOT_AVAILABLE: "MENU_NOT_AVAILABLE",
  RESTAURANT_TOO_FAR: "RESTAURANT_TOO_FAR",
  CAN_ORDER: "CAN_ORDER",
  USER_DID_NOT_ADD_LOCATION: "USER_DID_NOT_ADD_LOCATION",
} as const;
