export const KEYS = {
  BASE_URL: import.meta.env.VITE_BASE_URL,
  WEB_SOCKET_URL: import.meta.env.VITE_WEB_SOCKET_URL,
  ACCESS_TOKEN_KEY: import.meta.env.VITE_ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_KEY: import.meta.env.VITE_REFRESH_TOKEN_KEY,
  GOOGLE_AUTH_CLIENT_ID: import.meta.env.VITE_GOOGLE_AUTH_CLIENT_ID,
  GOOGLE_PLACE_API_KEY: import.meta.env.VITE_GOOGLE_PLACE_API_KEY,
  LOCATION_IN_LOCAL_STORAGE_KEY: import.meta.env
    .VITE_LOCATION_IN_LOCAL_STORAGE_KEY,
  PUBLIC_S3_PREFIX: import.meta.env.VITE_PUBLIC_S3_PREFIX,
  CART_IN_LOCAL_STORAGE: import.meta.env.VITE_CART_IN_LOCAL_STORAGE,
  FAKE_AVERAGE_RATING: import.meta.env.VITE_FAKE_AVERAGE_RATING,
  FAKE_TOTAL_NUMBER_OF_RATINGS: import.meta.env
    .VITE_FAKE_TOTAL_NUMBER_OF_RATINGS,
  MIN_RATINGS_BEFORE_SHOWING_REAL_RATINGS: import.meta.env
    .VITE_MIN_RATINGS_BEFORE_SHOWING_REAL_RATINGS,
  MAX_LOCATION_PROMPTS: import.meta.env.VITE_MAX_LOCATION_PROMPTS || 5,
  MAX_LOCATION_PROMPTS_IN_LOCAL_STORAGE: import.meta.env
    .VITE_MAX_LOCATION_PROMPTS_IN_LOCAL_STORAGE,
} as const;
